/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ParkingLot

import ParkingLot.management.System
import java.util.Scanner

val scanner = Scanner(java.lang.System.`in`)

fun main() {
    Parking.start()
}


object Parking {
    lateinit var parking: System

    fun start() {
        with(scanner) { while (true) {
            println(when (val command = next()) {
                "exit" -> return
                "create" -> {
                    val spots = nextInt()
                    parking = System(spots)
                    "Created a parking lot with $spots spots."
                }
                else ->
                    if (::parking.isInitialized) with(parking) { when (command) {
                        "park" -> park(next(), next())
                        "leave" -> leave(nextInt())
                        "status" -> toString()
                        "reg_by_color" -> regByColor(next())
                        "spot_by_color" -> spotByColor(next())
                        "spot_by_reg" -> spotByReg(next())
                        else -> "No such method!"
                    } }
                    else { nextLine(); "Sorry, a parking lot has not been created." }
            })
        } }
    }
}
